<?php
/**
 * @author Rix Beck <rix@neologik.hu>
 */

$query = <<<SQL
"SELECT
	p.nev as partner,  
	i.nev as iroda,  
	m.nev as tanacsado,  
	m.`aktiv` as tanacsado_aktiv,  
	tanacsado as felhasznalonev,  
	max(telefon_leutes) as telefon_leutes,  
	max(telefonalas) as telefonalas,  
	max(megbizas) as megbizas,  
	max(megbizas_kiado) as megbizas_kiado,  
	max(kizarolagos_megbizas) as kizarolagos_megbizas,  
	max(kizarolagos_arany) as kizarolagos_arany,  
	max(altalanos_megbizas) as altalanos_megbizas,  
	max(kiemelt_megbizas) as kiemelt_megbizas,  
	max(felezo_megbizas) as felezo_megbizas,  
	max(huseg_megbizas) as huseg_megbizas, 
	max(arlevitel) as arlevitel,  
	max(kapcsolattartas) as kapcsolattartas,  
	max(tranzakcio_elado_db) as tranzakcio_elado_db,  
	max(tranzakcio_elado_jutalek) as tranzakcio_elado_jutalek,  
	max(tranzakcio_kiado_db) as tranzakcio_kiado_db,  
	max(tranzakcio_kiado_jutalek) as tranzakcio_kiado_jutalek,  
	max(tranzakcio_kt_db) as tranzakcio_kt_db, 
	max(tranzakcio_kt_jutalek) as tranzakcio_kt_jutalek,  
  max(tranzakcio_elado_veteli_db) as tranzakcio_elado_veteli_db,  
	max(tranzakcio_elado_veteli_jutalek) as tranzakcio_elado_veteli_jutalek,  
	max(uj_cc_lead) as uj_cc_lead,  
	max(lezaratlan_cc_lead) as lezaratlan_cc_lead,  
	if(max(cc_aktiv_napok_szama)=-1,null,max(cc_aktiv_napok_szama)) as cc_aktiv_napok_szama, 
	max(uj_ugyfel) as uj_ugyfel,  
	max(uj_mappa) as uj_mappa,  
	max(mutatas) as mutatas,  
	max(mutatas_validalt) as mutatas_validalt,  
	max(mutatas_sajat) as mutatas_sajat,  
	max(mutatas_kereszt) as mutatas_kereszt,  
	max(veteli) as veteli,  
  max(veteli_validalt) as veteli_validalt,  
  max(tranzakcio_vevo_db) as tranzakcio_vevo_db,  
  max(tranzakcio_vevo_jutalek) as tranzakcio_vevo_jutalek,  
	max(tranzakcio_vevo_kiado_db) as tranzakcio_vevo_kiado_db,  
  max(tranzakcio_vevo_kiado_jutalek) as tranzakcio_vevo_kiado_jutalek,  
  max(tranzakcio_vevo_veteli_db) as tranzakcio_vevo_veteli_db,  
  max(tranzakcio_vevo_veteli_jutalek) as tranzakcio_vevo_veteli_jutalek,  
	max(portfolio) as portfolio,  
	max(portfolio_nem_kezelt) as portfolio_nem_kezelt,  
	max(portfolio_lejaro) as portfolio_lejaro,  
	max(sikeridopont) as sikeridopont,  
	max(kikerulo_ingatlan) as kikerulo_ingatlan,  
	max(vevo_kapcsolattartas) as vevo_kapcsolattartas, 
	max(kereso_ugyfelek_szama) as kereso_ugyfelek_szama, 
	max(mappak_szama) as mappak_szama, 
	max(nem_kezelt_ugyfel) as nem_kezelt_ugyfel, 
	max(nem_kezelt_mappa) as nem_kezelt_mappa, 
	max(elbukott_darab)  as elbukott_darab, 
	max(elbukott_forint) as elbukott_forint, 
	max(elbukott_iroda_darab) as elbukott_iroda_darab, 
	max(elbukott_iroda_forint) as elbukott_iroda_forint, 
	max(elbukott_partner_darab) as elbukott_partner_darab, 
	max(elbukott_partner_forint) as elbukott_partner_forint, 
	if(max(ugyfel_elegedettseg)=-1,null,max(ugyfel_elegedettseg)) as ugyfel_elegedettseg, 
	if(max(ugyfel_elegedettseg_1ho)=-1,null,max(ugyfel_elegedettseg_1ho)) as ugyfel_elegedettseg_1ho, 
	max(energetika_kulsos) as energetika_kulsos, 
	max(energetika_sajat) as energetika_sajat, 
	max(kereszthirdetes) as kereszthirdetes, 
	max(kereszthirdetes_uj) as kereszthirdetes_uj, 
	max(kepzes) as kepzes 
		  FROM (  
SELECT   
	tanacsado,  
    0 as telefon_leutes,  
    0 as telefonalas,  
    count(if(i.ertekesites='elado',i.regszam,null)) as megbizas,  
		count(if(i.ertekesites='kiado',i.regszam,null)) as megbizas_kiado,  
    count(if(i.ertekesites='elado' AND i.`megbizas_tipusa_validalaskor` in ('kiemelt','komfort','komfort_siker','felezo','huseg'),i.regszam,null)) as kizarolagos_megbizas,  
    count(if(i.ertekesites='elado' AND i.`megbizas_tipusa_validalaskor` in ('kiemelt','komfort','komfort_siker','felezo','huseg'),i.regszam,null))/count(if(i.ertekesites='elado',i.regszam,null)) as kizarolagos_arany,  
		count(if(i.ertekesites='elado' AND i.`megbizas_tipusa_validalaskor` = 'altalanos',i.regszam,null)) as altalanos_megbizas,  
		count(if(i.ertekesites='elado' AND i.`megbizas_tipusa_validalaskor` = 'kiemelt',i.regszam,null)) as kiemelt_megbizas,  
		count(if(i.ertekesites='elado' AND i.`megbizas_tipusa_validalaskor` = 'felezo',i.regszam,null)) as felezo_megbizas,  
		count(if(i.ertekesites='elado' AND i.`megbizas_tipusa_validalaskor` = 'huseg',i.regszam,null)) as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
    0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
	0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
	0 as tranzakcio_vevo_jutalek,  
	0 as tranzakcio_vevo_kiado_db,  
	0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio, 
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas , 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0  as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM hiper_ingatlan i  
WHERE   
	i.`elso_validalas_datuma` between " ~ params['date_from'] ~ "  AND " ~ params['date_to'] ~ "
	AND i.`source_system`=''  
GROUP BY tanacsado  
  
UNION   
SELECT  
    t.tanacsado_elado as tanacsado,  
    0 as telefon_leutes,  
    0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany, 
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	count(if(t.ugyfel_vevo not between -2 AND 0 AND t.jutalekft>0 AND i.ertekesites='elado',t.regszam,null)) as tranzakcio_elado_db,  
	sum(if(t.ugyfel_vevo not between -2 AND 0 AND t.jutalekft>0  AND i.ertekesites='elado',t.`jutalek_elado`,0)) as tranzakcio_elado_jutalek,  
	count(if(t.ugyfel_vevo not between -2 AND 0 AND t.jutalekft>0  AND i.ertekesites='kiado',t.regszam,null)) as tranzakcio_kiado_db,  
	sum(if(t.ugyfel_vevo not between -2 AND 0 AND t.jutalekft>0  AND i.ertekesites='kiado',t.`jutalek_elado`,0)) as tranzakcio_kiado_jutalek,  
	count(if(t.ugyfel_vevo in (-1,-2) AND t.jutalekft > 0 AND t.ingatlan_sorsa!='aktualis',t.regszam,null)) as tranzakcio_kt_db,  
	sum(  if(t.ugyfel_vevo in (-1,-2) AND t.jutalekft > 0 AND t.ingatlan_sorsa!='aktualis',t.`jutalek_elado`,0)) as tranzakcio_kt_jutalek,  
  count(if(t.ugyfel_vevo in (-1,-2) AND t.jutalekft > 0 AND t.ingatlan_sorsa='aktualis', t.regszam,null)) as tranzakcio_elado_veteli_db,  
	sum(  if(t.ugyfel_vevo in (-1,-2) AND t.jutalekft > 0 AND t.ingatlan_sorsa='aktualis', t.jutalek_elado,0)) as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
	0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
	0 as tranzakcio_vevo_jutalek,  
	0 as tranzakcio_vevo_kiado_db,  
	0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	count(if(t.jutalekft=0,t.regszam,null)) as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas , 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0  as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM hiper_tranzakcio t   
    INNER JOIN hiper_ingatlan i ON i.id=t.id_realestate AND t.`lezaras_tipusa`<4 AND t.`statusz`='lezarva'
WHERE  
    t.`lezaras_datuma` between " ~ params['date_from'] ~ "  AND " ~ params['date_to'] ~ "
    and  i.`source_system`=''  
GROUP BY t.`tanacsado_elado`  
  
  
UNION  
SELECT  
    t.`tanacsado_vevo` as tanacsado,  
    0 as telefon_leutes,  
    0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany, 
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas,  
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
  0 as veteli_validalt,  
	count(if(t.ugyfel_vevo not between -2 AND 0 AND i.ertekesites='elado',t.regszam,null)) as tranzakcio_vevo_db,  
	sum(if(t.ugyfel_vevo not between -2 AND 0 AND i.ertekesites='elado',t.`jutalek_vevo`,0)) as tranzakcio_vevo_jutalek,  
	count(if(t.ugyfel_vevo not between -2 AND 0 AND i.ertekesites='kiado',t.regszam,null)) as tranzakcio_vevo_kiado_db,  
	sum(if(t.ugyfel_vevo not between -2 AND 0 AND i.ertekesites='kiado',t.`jutalek_vevo`,0)) as tranzakcio_vevo_kiado_jutalek,  
  count(if(t.ugyfel_vevo in (-1,-2) AND t.jutalekft > 0 AND t.ingatlan_sorsa='aktualis', t.regszam,null)) as tranzakcio_vevo_veteli_db,  
	sum(  if(t.ugyfel_vevo in (-1,-2) AND t.jutalekft > 0 AND t.ingatlan_sorsa='aktualis', t.jutalek_vevo,0)) as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas  , 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0 as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM hiper_tranzakcio t   
    INNER JOIN hiper_ingatlan i ON i.id=t.id_realestate AND t.`lezaras_tipusa`<4 AND t.`statusz`='lezarva' AND t.jutalekft>0 
WHERE  
    t.`lezaras_datuma` between " ~ params['date_from'] ~ "  AND " ~ params['date_to'] ~ "  
GROUP BY t.`tanacsado_vevo`  
  
UNION  
SELECT  
	l.`eredeti_tanacsado` as tanacsado,  
	0 as telefon_leutes,  
	0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	count(l.id_lead) as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
	0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
	0 as tranzakcio_vevo_jutalek,  
	0 as tranzakcio_vevo_kiado_db,  
	0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas  , 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0  as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM hiper_lead l   
  
WHERE  
    l.`date_created` between " ~ params['date_from'] ~ "  AND " ~ params['date_to'] ~ "  
GROUP BY l.`eredeti_tanacsado`  
  
UNION  
SELECT  
	l.`tanacsado` as tanacsado,  
	0 as telefon_leutes,  
	0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	count(id_lead) as lezaratlan_cc_lead, 
	-1 as cc_aktiv_napok_szama,  
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
    0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
    0 as tranzakcio_vevo_jutalek,  
    0 as tranzakcio_vevo_kiado_db,  
    0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas  , 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0  as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM hiper_lead l   
  
WHERE  
    l.`closed`=0  
GROUP BY l.`tanacsado`  
  
UNION  
SELECT  
    u.`tanacsado` as tanacsado,  
    0 as telefon_leutes,  
    0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	count(u.id) as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
    0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
    0 as tranzakcio_vevo_jutalek,  
    0 as tranzakcio_vevo_kiado_db,  
    0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas  , 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0  as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM hiper_ugyfel u  
  
WHERE  
    u.`letrehozva` between " ~ params['date_from'] ~ "  AND " ~ params['date_to'] ~ "  
GROUP BY u.`tanacsado`  
  
UNION  
SELECT  
    m.`tanacsado` as tanacsado,  
    0 as telefon_leutes,  
    0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	count(DISTINCT m.id) as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
    0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
    0 as tranzakcio_vevo_jutalek,  
    0 as tranzakcio_vevo_kiado_db,  
    0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas  , 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0  as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM hiper_mappa m  
WHERE  
    m.`date_created` between " ~ params['date_from'] ~ "  AND " ~ params['date_to'] ~ "  
GROUP BY m.`tanacsado`  
  
 UNION  
SELECT  
    ik.`id_tanacsado` as tanacsado,  
    0 as telefon_leutes,  
    0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	count(*) as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
    0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
    0 as tranzakcio_vevo_jutalek,  
    0 as tranzakcio_vevo_kiado_db,  
    0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas  , 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0  as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM hiper_ingatlan_kapcsolattartas ik  
WHERE  
    ik.`date_created` between " ~ params['date_from'] ~ "  AND " ~ params['date_to'] ~ "  
GROUP BY ik.id_tanacsado  
 
 
  UNION  
SELECT  
    pms.`id_tanacsado` as tanacsado,  
    sum(pms.search) as telefon_leutes,  
    sum(pms.call) as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
    0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
    0 as tranzakcio_vevo_jutalek,  
    0 as tranzakcio_vevo_kiado_db,  
    0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	sum(pms.success_call) as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas  , 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0  as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM phonemodul_stat pms  
WHERE  
    pms.date between " ~ params['date_from'] ~ "  AND " ~ params['date_to'] ~ "  
GROUP BY pms.id_tanacsado  
  
UNION  
SELECT  
    ny.`tanacsado` as tanacsado,  
    0 as telefon_leutes,  
    0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	count(DISTINCT if(ny.`statusz` in (1,2),nyi.`regszam`,null),if(ny.`statusz` in (1,2),ny.`ugyfel`,null)) as mutatas,  
	count(DISTINCT if(ny.`statusz`='2',nyi.`regszam`,null),if(ny.`statusz`='2',ny.`ugyfel`,null)) as mutatas_validalt,  
	count(DISTINCT if(ny.tanacsado = i.tanacsado and ny.`statusz` in (1,2),nyi.`regszam`,null),if(ny.tanacsado = i.tanacsado and ny.`statusz` in (1,2),ny.`ugyfel`,null)) as mutatas_sajat,  
	count(DISTINCT if(ny.tanacsado != i.tanacsado and ny.`statusz` in (1,2),nyi.`regszam`,null),if(ny.tanacsado != i.tanacsado and ny.`statusz` in (1,2),ny.`ugyfel`,null)) as mutatas_kereszt,  
	0 as veteli,  
    0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
    0 as tranzakcio_vevo_jutalek,  
    0 as tranzakcio_vevo_kiado_db,  
    0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas  , 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0  as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM `hiper_nyomtatvany` ny  
	INNER JOIN `hiper_nyomtatvany_ingatlan` nyi ON nyi.`id_nyomtatvany`=ny.`id` AND nyi.`statusz`=1   
	INNER JOIN hiper_ingatlan i ON nyi.regszam=i.regszam_projekt_group AND i.ertekesites='elado'   
WHERE  
    nyi.`megtekintes_idopont` between " ~ params['date_from'] ~ "  AND " ~ params['date_to'] ~ "  
    AND ny.`tipus` in ('XNY','FMN','AMN','UMN','EMN','EFN')  
GROUP BY ny.`tanacsado`  
  
  
  
UNION  
SELECT  
    ny.`tanacsado` as tanacsado,  
    0 as telefon_leutes,  
    0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	COUNT(DISTINCT ny.id) as veteli,  
    COUNT(DISTINCT if(ny.`statusz`='2',ny.`id`,null))  as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
    0 as tranzakcio_vevo_jutalek,  
    0 as tranzakcio_vevo_kiado_db,  
    0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas  , 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0  as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM `hiper_nyomtatvany` ny  
 INNER JOIN hiper_ingatlan i ON ny.ingatlan=i.regszam AND i.ertekesites='elado'  
WHERE  
	ny.`letrehozva` between " ~ params['date_from'] ~ "  AND " ~ params['date_to'] ~ "  
   AND  ny.`tipus` in ('VA','VNY','UVA','FVA')  
GROUP BY ny.`tanacsado`  
  
  
UNION  
SELECT   
	i.tanacsado,  
    0 as telefon_leutes,  
    0 as telefonalas,  
    0 as megbizas,  
  	0 as megbizas_kiado,  
   0 as kizarolagos_megbizas,  
    0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	count(ie.id) as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
    0 as veteli_validalt,  
    0 as tranzakcio_vevo_db,  
    0 as tranzakcio_vevo_jutalek,  
    0 as tranzakcio_vevo_kiado_db,  
    0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas , 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0  as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM hiper_ingatlan i  
    INNER JOIN hiper_ingatlan_ertekesites ie ON ie.regszam=i.regszam AND ie.arcsokkenes='1' AND if(ie.regi_iranyar>ie.iranyar,ie.regi_iranyar-ie.iranyar,0)/ie.regi_iranyar>=0.035 AND ie.letrehozva between " ~ params['date_from'] ~ "  AND " ~ params['date_to'] ~ "  
WHERE   
	i.`source_system`=''  
    AND i.`projekt`=''  
	AND i.ertekesites='elado'  
GROUP BY i.tanacsado  
  
  
UNION  
SELECT   
	tanacsado,  
    0 as telefon_leutes,  
    0 as telefonalas,  
    0 as megbizas,  
 	0 as megbizas_kiado,  
   0 as kizarolagos_megbizas,  
    0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
    0 as veteli_validalt,  
    0 as tranzakcio_vevo_db,  
    0 as tranzakcio_vevo_jutalek,  
    0 as tranzakcio_vevo_kiado_db,  
    0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	count(i.regszam) as portfolio,  
	count(if(i.nem_kezelt_megbizas,i.regszam,null)) as portfolio_nem_kezelt,  
	count(if(i.megbiz_szerz_lejaratidatum between (" ~ params['date_to'] ~ " + INTERVAL 1 SECOND) AND (" ~ params['date_to'] ~ " + INTERVAL DATEDIFF(" ~ params['date_to'] ~ ", " ~ params['date_from'] ~ ")+1 DAY),i.regszam,null)) as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas , 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0  as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM hiper_ingatlan i  
WHERE   
	i.statusz='aktualis'  
	AND i.`source_system`=''  
    AND i.`projekt`=''  
	AND i.ertekesites='elado'  
GROUP BY tanacsado  
  
  UNION  
SELECT  
    ik.`id_tanacsado` as tanacsado,  
    0 as telefon_leutes,  
    0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
    0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
    0 as tranzakcio_vevo_jutalek,  
    0 as tranzakcio_vevo_kiado_db,  
    0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	count(*) as vevo_kapcsolattartas  , 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0  as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM hiper_mappa_kapcsolattartas ik  
WHERE  
    ik.`date_created` between " ~ params['date_from'] ~ "  AND " ~ params['date_to'] ~ "  
GROUP BY ik.id_tanacsado  
 UNION 
 SELECT  
    m.`tanacsado` as tanacsado,  
    0 as telefon_leutes,  
    0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	count(DISTINCT m.id) as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
    0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
    0 as tranzakcio_vevo_jutalek,  
    0 as tranzakcio_vevo_kiado_db,  
    0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas, 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0  as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
 
FROM hiper_mappa m  
WHERE  
    m.`date_created` between " ~ params['date_from'] ~ "  AND " ~ params['date_to'] ~ "  
GROUP BY m.`tanacsado` 
UNION 
 
SELECT  
    m.`tanacsado` as tanacsado,  
    0 as telefon_leutes,  
    0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
    0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
    0 as tranzakcio_vevo_jutalek,  
    0 as tranzakcio_vevo_kiado_db,  
    0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas, 
	count(DISTINCT m.ugyfel) as kereso_ugyfelek_szama, 
	count(DISTINCT m.id) as mappak_szama, 
	count(DISTINCT if(m.nem_kezelt_mappa=1,m.ugyfel,null)) as nem_kezelt_ugyfel, 
	count(DISTINCT if(m.nem_kezelt_mappa=1,m.id, null)) as nem_kezelt_mappa, 
	0  as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM hiper_mappa m  
WHERE  
    m.statusz='0' 
GROUP BY m.`tanacsado`  
  
 UNION 
 SELECT  
    mvu.`tanacsado` as tanacsado,  
    0 as telefon_leutes,  
    0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
    0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
    0 as tranzakcio_vevo_jutalek,  
    0 as tranzakcio_vevo_kiado_db,  
    0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas, 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	count(if(mvu.tanacsado!=mvu.vevo_tanacsado AND mvu.iroda=mvu.vevo_iroda,mvu.id_tranzakcio,null))  as elbukott_darab, 
	sum(if(mvu.tanacsado!=mvu.vevo_tanacsado AND mvu.iroda=mvu.vevo_iroda, mvu.jutalek_vevo,null)) as elbukott_forint, 
	count(if(mvu.iroda!=mvu.vevo_iroda AND mvu.partner=mvu.vevo_partner ,mvu.id_tranzakcio,null)) as elbukott_iroda_darab, 
	sum(if(mvu.iroda!=mvu.vevo_iroda AND mvu.partner=mvu.vevo_partner, mvu.jutalek_vevo,null)) as elbukott_iroda_forint, 
	count(if(mvu.partner!=mvu.vevo_partner,mvu.id_tranzakcio,null)) as elbukott_partner_darab, 
	sum(if(mvu.partner!=mvu.vevo_partner,mvu.jutalek_vevo,null)) as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM hiper_tranzakcio_mas_vevo_tanacsado mvu 
INNER JOIN hiper_tranzakcio t ON mvu.id_tranzakcio=t.id 
WHERE  
    mvu.tanacsado!=mvu.vevo_tanacsado 
		AND t.lezaras_datuma between " ~ params['date_from'] ~ "  AND " ~ params['date_to'] ~ " 
GROUP BY mvu.`tanacsado`  
 UNION 
  SELECT  
    t.`id_tanacsado` as tanacsado,  
    0 as telefon_leutes,  
    0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
    0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
    0 as tranzakcio_vevo_jutalek,  
    0 as tranzakcio_vevo_kiado_db,  
    0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas, 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0 as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	avg(last_rate) ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM ( 
SELECT id_ugyfel, id_tanacsado, count(*) as felkeresek_szama, max(date_last_answer) as last_answer from hiper_ugyfel_elegedettseg ue 
WHERE 
(date_last_answer BETWEEN date_format(" ~ params['date_to'] ~ "-interval 6 MONTH,'%Y-%m-01 00:00:00') AND date_format(" ~ params['date_to'] ~ ",'%Y-%m-01 23:59:59') - interval 1 DAY 
or (date_created BETWEEN date_format(" ~ params['date_to'] ~ "-interval 6 MONTH,'%Y-%m-01 00:00:00') AND date_format(" ~ params['date_to'] ~ ",'%Y-%m-01 23:59:59') - interval 1 DAY	AND ue.last_rate is null)) 
group by id_ugyfel, id_tanacsado) as t  
LEFT JOIN hiper_ugyfel_elegedettseg ue ON t.id_ugyfel=ue.id_ugyfel AND t.id_tanacsado=ue.id_tanacsado AND last_answer=date_last_answer 
 
GROUP BY t.`id_tanacsado`  
 
UNION 
  SELECT  
    t.`id_tanacsado` as tanacsado,  
    0 as telefon_leutes,  
    0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
    0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
    0 as tranzakcio_vevo_jutalek,  
    0 as tranzakcio_vevo_kiado_db,  
    0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas, 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0 as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	avg(last_rate) ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM ( 
SELECT id_ugyfel, id_tanacsado, count(*) as felkeresek_szama, max(date_last_answer) as last_answer from hiper_ugyfel_elegedettseg ue 
WHERE 
(date_last_answer BETWEEN date_format(" ~ params['date_to'] ~ "-interval 1 MONTH,'%Y-%m-01 00:00:00') AND date_format(" ~ params['date_to'] ~ ",'%Y-%m-01 23:59:59') - interval 1 DAY 
or (date_created BETWEEN date_format(" ~ params['date_to'] ~ "-interval 1 MONTH,'%Y-%m-01 00:00:00') AND date_format(" ~ params['date_to'] ~ ",'%Y-%m-01 23:59:59') - interval 1 DAY	AND ue.last_rate is null)) 
group by id_ugyfel, id_tanacsado) as t  
LEFT JOIN hiper_ugyfel_elegedettseg ue ON t.id_ugyfel=ue.id_ugyfel AND t.id_tanacsado=ue.id_tanacsado AND last_answer=date_last_answer 
 
GROUP BY t.`id_tanacsado`  
 
UNION 
 
 SELECT  
  ul.`id_tanacsado` as tanacsado,  
  0 as telefon_leutes,  
  0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
  0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
  0 as tranzakcio_vevo_jutalek,  
  0 as tranzakcio_vevo_kiado_db,  
  0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas, 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0 as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	count(*) as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
 
FROM hiper_ujenergetika_lead ul 
WHERE  
		megrendeles_statusz = 2 
    AND ul.tanusitvany_datum between " ~ params['date_from'] ~ "  AND " ~ params['date_to'] ~ "  
GROUP BY ul.`id_tanacsado` 
 
UNION 
 
 SELECT  
  ul.`tanacsado` as tanacsado,  
  0 as telefon_leutes,  
  0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
  0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
  0 as tranzakcio_vevo_jutalek,  
  0 as tranzakcio_vevo_kiado_db,  
  0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas, 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0 as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	count(*) as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
	 
 
FROM hiper_ocs_et ul 
WHERE  
    ul.statusz = 2 
		AND ul.tanusitvany_datum between " ~ params['date_from'] ~ "  AND " ~ params['date_to'] ~ "  
GROUP BY ul.`tanacsado`  
 
UNION 
 
 SELECT  
  kh.`id_tanacsado` as tanacsado,  
  0 as telefon_leutes,  
  0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	-1 as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
  0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
  0 as tranzakcio_vevo_jutalek,  
  0 as tranzakcio_vevo_kiado_db,  
  0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas, 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0 as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	count(DISTINCT id_ingatlan) as kereszthirdetes, 
	count(DISTINCT IF(kh.date_created BETWEEN " ~ params['date_from'] ~ " AND " ~ params['date_to'] ~ ",id_ingatlan,null)) as kereszthirdetes_uj, 
	0 as kepzes 
 
FROM hiper_hm_ingatlan_kereszthirdetes kh 
INNER JOIN hiper_munkatars m ON kh.id_tanacsado = m.felhasznalonev AND m.aktiv=1 
WHERE  
    kh.status in (1,2) 
		AND kh.date_created < " ~ params['date_to'] ~ " 
		AND kh.date_deleted is null or date_deleted>" ~ params['date_from'] ~ " 
GROUP BY kh.`id_tanacsado`  
 
UNION 
SELECT  
	l.`eredeti_tanacsado` as tanacsado,  
	0 as telefon_leutes,  
	0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
    IF(COUNT(*)>0, AVG(DATEDIFF(ifnull(date_closed," ~ params['date_to'] ~ "),date_created)),-1)	as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
	0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
	0 as tranzakcio_vevo_jutalek,  
	0 as tranzakcio_vevo_kiado_db,  
	0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas  , 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0 as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	0 as kepzes 
FROM hiper_lead l   
  
WHERE  
    l.`date_created` < " ~ params['date_to'] ~ " 
		AND (l.`date_created` > " ~ params['date_from'] ~ " OR l.`date_created` is null) 
GROUP BY l.`eredeti_tanacsado`  
 
UNION 
 
SELECT  
	m.felhasznalonev as tanacsado,  
	0 as telefon_leutes,  
	0 as telefonalas,  
	0 as megbizas,  
	0 as megbizas_kiado,  
	0 as kizarolagos_megbizas,  
	0 as kizarolagos_arany,  
	0 as altalanos_megbizas,  
	0 as kiemelt_megbizas,  
	0 as felezo_megbizas,  
	0 as huseg_megbizas, 
	0 as arlevitel,  
	0 as kapcsolattartas,  
	0 as tranzakcio_elado_db,  
	0 as tranzakcio_elado_jutalek,  
	0 as tranzakcio_kiado_db,  
	0 as tranzakcio_kiado_jutalek,  
	0 as tranzakcio_kt_db, 
	0 as tranzakcio_kt_jutalek,  
  0 as tranzakcio_elado_veteli_db,  
	0 as tranzakcio_elado_veteli_jutalek,  
	0 as uj_cc_lead,  
	0 as lezaratlan_cc_lead,  
	0	as cc_aktiv_napok_szama, 
	0 as uj_ugyfel,  
	0 as uj_mappa,  
	0 as mutatas,  
	0 as mutatas_validalt,  
	0 as mutatas_sajat,  
	0 as mutatas_kereszt,  
	0 as veteli,  
	0 as veteli_validalt,  
	0 as tranzakcio_vevo_db,  
	0 as tranzakcio_vevo_jutalek,  
	0 as tranzakcio_vevo_kiado_db,  
	0 as tranzakcio_vevo_kiado_jutalek,  
	0 as tranzakcio_vevo_veteli_db,  
  0 as tranzakcio_vevo_veteli_jutalek,  
	0 as portfolio,  
	0 as portfolio_nem_kezelt,  
	0 as portfolio_lejaro,  
	0 as sikeridopont,  
	0 as kikerulo_ingatlan,  
	0 as vevo_kapcsolattartas, 
	0 as kereso_ugyfelek_szama, 
	0 as mappak_szama, 
	0 as nem_kezelt_ugyfel, 
	0 as nem_kezelt_mappa, 
	0 as elbukott_darab, 
	0 as elbukott_forint, 
	0 as elbukott_iroda_darab, 
	0 as elbukott_iroda_forint, 
	0 as elbukott_partner_darab, 
	0 as elbukott_partner_forint, 
	-1 as ugyfel_elegedettseg, 
	-1 as ugyfel_elegedettseg_1ho, 
	0 as energetika_kulsos, 
	0 as energetika_sajat, 
	0 as kereszthirdetes, 
	0 as kereszthirdetes_uj, 
	count(*) as kepzes 
FROM hiper_munkatars_kurzus mk LEFT JOIN hiper_munkatars m ON m.id=mk.id_employee 
WHERE  
    mk.is_finished=1 AND mk.date_finished BETWEEN " ~ params['date_from'] ~ " AND " ~ params['date_to'] ~ " 
GROUP BY mk.id_employee 

	                                    
) adatok  
LEFT JOIN hiper_munkatars m ON adatok.tanacsado=m.`felhasznalonev`  
LEFT JOIN hiper_iroda i ON m.iroda=i.`azonosito`  
LEFT JOIN hiper_partner p ON i.`partner`=p.id  
WHERE m.`felhasznalonev` is not null AND p.id is not null " ~
(params['partner'] ? " AND i.partner in (" ~ implode(',',params['partner']) ~ ") " : " ") ~
(params['terulet'] ? " AND i.id_terulet in (" ~ implode(',',params['terulet']) ~ ") " : " ") ~
(params['iroda'] ? " AND i.azonosito in (" ~ params['iroda'] ~ ") " : " ") ~
(params['munkatars'] ? " AND m.felhasznalonev  in (" ~ params['munkatars'] ~ ") " : " ") ~
" GROUP BY adatok.tanacsado 
ORDER BY partner, iroda, tanacsado"

SQL;

return $query;
